#!/usr/bin/env python
import getpass
import json
import requests
import sys


def racker_auth():
    password = getpass.getpass("Password: ")
    url = 'https://identity-internal.api.rackspacecloud.com/v2.0/tokens'
    data = {
        "auth": {
            "RAX-AUTH:domain": {
                "name": "Rackspace"
            },
            "passwordCredentials": {
                "username": user,
                "password": password
            }
        }
    }
    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    req = requests.post(url, data=json.dumps(data), headers=headers)
    token = req.json()['access']['token']['id']
    return token


def impersonate(account, token):
    url = ('https://identity-internal.api.rackspacecloud.com'
           '/v2.0/RAX-AUTH/impersonation-tokens')
    data = {
        "RAX-AUTH:impersonation": {
            "user": {
                "username": 'hybrid'+account
            },
            "expire-in-seconds": 10800
        }
    }
    headers = {
        "Content-type": "application/json",
        "X-Auth-Token": token
    }
    req = requests.post(url, data=json.dumps(data), headers=headers)
    return req.json()['access']['token']['id']


def get_monitoring_info(account, token):
    url = ('https://monitoring.api.rackspacecloud.com'
           '/v1.0/hybrid:%s/views/overview' % account)
    headers = {
        "Content-type": "application/json",
        "X-Auth-Token": token
    }
    req = requests.get(url, headers=headers)
    return req.json()


if __name__ == '__main__':
    try:
        user = sys.argv[1]
        account = sys.argv[2]
    except IndexError:
        print ('cloud-token <UserName> <Account-Num>')
        sys.exit(2)
    else:
        token = racker_auth()
        # print token
        impersonation = impersonate(account, token)
        print (impersonation)
